# This job builds and deploys the lambda function to aws lambda

name: Deploy to AWS Lambda

on:
  push:
    branches: [ master ]

jobs:  
  build_and_deploy:
    runs-on: ubuntu-latest
    env: 
      ACTIONS_ALLOW_UNSECURE_COMMANDS: true
    steps:
      - name: Set Environment Variables
        run: echo '::set-env name=ACTIONS_ALLOW_UNSECURE_COMMANDS::true' && '::set-env name=AWS_ACCESS_KEY_ID::${{secrets.AWS_ACCESS_KEY_ID}}' && echo '::set-env name=AWS_SECRET_ACCESS_KEY::${{secrets.AWS_SECRET_ACCESS_KEY}}'
      
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.1
        with:
          node-version: 14.x

      - name: Clone Repository
        uses: actions/checkout@v2
      
      - name: Install node modules
        run: npm install

      - name: Perform Build
        run: npm run build

      - name: Deploy to AWS
        run: npm run deploy
