# This job builds and deploys the lambda function to aws lambda

name: Deploy to AWS Lambda

on:
  push:
    branches: [ master ]

jobs:  
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.1
        with:
          node-version: 12.x

      - name: Clone Repository
        uses: actions/checkout@v2
      
      - name: Set Environment Variables
        run: echo '::set-env name=AWS_ACCESS_KEY_ID::${{secrets.AWS_ACCESS_KEY_ID}}' && echo '::set-env name=AWS_SECRET_ACCESS_KEY::${{secrets.AWS_SECRET_ACCESS_KEY}}'
      - name: Install node modules
        run: npm install

      - name: Perform Build
        run: npm run build

      - name: Deploy to AWS
        run: npm run deploy
